name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - name: ESLint Action
      uses: hallee/eslint-action@1.0.1
